version: '2'

services:
  cassandra-service:
    image: thingsbypragma/cassandra:dev
    volumes:
      - ./cassandra_dev/volumescassandra:/var/lib/cassandra
    ports:
      - "9042:9042"

  commerce-api:
    image: thingsbypragma/tomcat:dev
    volumes:
      - ./volumestomcat/tomcat_dev/commerce:/usr/local/tomcat/commerce
    command: ["/wait-for-it.sh", "cassandra-service:9042", "--", "/usr/local/tomcat/bin/catalina.sh", "run"]
    depends_on:
      - cassandra-service
    ports:
      - "4000:4000"